# Generated by Django 3.1.7 on 2021-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ap_id",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="Jules", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="remote",
            field=models.BooleanField(default=False),
        ),
    ]
