# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-01-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210126_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='recipe',
            new_name='recipes',
        ),
    ]
