[tool.pylint.MESSAGE_CONTROL]
disable="""
    bad-continuation,
    no-else-return,
    too-few-public-methods,
    line-too-long,
    duplicate-code,
    import-error,
    unused_variable,
    no-self-use,
    import-outside-toplevel,
    fixme,
    missing-function-docstring,
    missing-class-docstring,
    missing-module-docstring,
    no-member
"""

[tool.pylint.REPORTS]
reports="no"

[tool.pylint.FORMAT]
max-line-length="88"

[tool.pylint.BASIC]
good-names="_,i,j,k,e,qs,pk,setUp,tearDown,maxDiff,default_app_config,app_name"

[tool.black]
line-length = 88
include = '\.pyi?$'

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
default_section = "THIRDPARTY"
known_first_party = ["cookbook", "recipes", "users"]
known_third_party = ["django", "recipe_scrapers", "requests"]
