# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-02-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0002_auto_20210124_1110'),
        ('users', '0004_auto_20210202_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.cookbook')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipe')),
            ],
        ),
    ]
