# Generated by Django 3.1.7 on 2021-02-28 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cookbook",
            fields=[
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cookbook",
                        serialize=False,
                        to="users.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cookbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cookbook.cookbook",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="recipes.recipe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cookbook",
            name="recipes",
            field=models.ManyToManyField(through="cookbook.Entry", to="recipes.Recipe"),
        ),
    ]
