# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-02-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210124_1110'),
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbook',
            name='recipes',
            field=models.ManyToManyField(through='cookbook.Entry', to='recipes.Recipe'),
        ),
    ]
