# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-02-02 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0002_cookbook_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbook',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cookbook', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
