# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-01-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
