# Generated by Django 3.1.5 on 2021-01-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210114_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
