# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-02-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210202_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity_unit',
            field=models.CharField(default='grams', max_length=200),
            preserve_default=False,
        ),
    ]
