# Generated by Django 3.1.5 on 2021-01-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210120_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
