# -*- coding: utf-8 -*-
# Generated by Django 3.1.5 on 2021-02-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210203_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
