# Generated by Django 3.1.7 on 2021-03-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_auto_20210302_1418"),
        ("recipes", "0005_auto_20210302_1422"),
    ]

    operations = []
