# Generated by Django 3.1.5 on 2021-02-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210205_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='diet',
        ),
        migrations.AddField(
            model_name='recipe',
            name='diets',
            field=models.ManyToManyField(to='recipes.RestrictedDiet'),
        ),
    ]
