# Generated by Django 3.1.7 on 2021-03-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_merge_20210306_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='number_references',
            field=models.IntegerField(default=1),
        ),
    ]
