# Generated by Django 3.1.7 on 2021-03-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_auto_20210307_1012"),
        ("recipes", "0007_auto_20210307_1634"),
    ]

    operations = []
