# Generated by Django 3.1.7 on 2021-03-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_merge_20210307_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ap_id',
            field=models.TextField(default=None, null=True),
        ),
    ]
