# Generated by Django 3.1.7 on 2021-03-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210308_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ap_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diets',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.RestrictedDiet'),
        ),
    ]
